services:
  vm_escape:
    build: . # Dockerfile location
    ports:
      - "127.0.0.1:1337:1337" # EXTERNAL_PORT:INTERNAL_PORT
      - "127.0.0.1:1338:1338" # EXTERNAL_PORT:INTERNAL_PORT
    restart: always # Always restart the container if it stops
    cap_drop:
      - ALL